default_agent: strands_chat_agent
agents:
  strands_chat_agent:
    name: strands_chat_agent
    entrypoint: /Users/schinnacha001/Desktop/Agentcore-demo/Blog/Bedrock_AgentCore_Strands_ChatAgent/agents/strands_chat_agent.py
    deployment_type: container
    runtime_type: null
    platform: linux/arm64
    container_runtime: none
    source_path: null
    aws:
      execution_role: arn:aws:iam::154594000270:role/AmazonBedrockAgentCoreSDKRuntime-us-east-1-8bb08c2ceb
      execution_role_auto_create: false
      account: '154594000270'
      region: us-east-1
      ecr_repository: 154594000270.dkr.ecr.us-east-1.amazonaws.com/bedrock-agentcore-strands_chat_agent
      ecr_auto_create: false
      s3_path: null
      s3_auto_create: false
      network_configuration:
        network_mode: PUBLIC
        network_mode_config: null
      protocol_configuration:
        server_protocol: HTTP
      observability:
        enabled: true
      lifecycle_configuration:
        idle_runtime_session_timeout: null
        max_lifetime: null
    bedrock_agentcore:
      agent_id: strands_chat_agent-y4N2QYBYXG
      agent_arn: arn:aws:bedrock-agentcore:us-east-1:154594000270:runtime/strands_chat_agent-y4N2QYBYXG
      agent_session_id: null
    codebuild:
      project_name: bedrock-agentcore-strands_chat_agent-builder
      execution_role: arn:aws:iam::154594000270:role/AmazonBedrockAgentCoreSDKCodeBuild-us-east-1-8bb08c2ceb
      source_bucket: bedrock-agentcore-codebuild-sources-154594000270-us-east-1
    memory:
      mode: NO_MEMORY
      memory_id: null
      memory_arn: null
      memory_name: null
      event_expiry_days: 30
      first_invoke_memory_check_done: false
      was_created_by_toolkit: false
    identity:
      credential_providers: []
      workload: null
    aws_jwt:
      enabled: false
      audiences: []
      signing_algorithm: ES384
      issuer_url: null
      duration_seconds: 300
    authorizer_configuration: null
    request_header_configuration: null
    oauth_configuration: null
    api_key_env_var_name: null
    api_key_credential_provider_name: null
    is_generated_by_agentcore_create: false
